USE [master]
GO

WHILE EXISTS(select NULL from sys.databases where name='QLCC')
BEGIN
    DECLARE @SQL varchar(max)
    SELECT @SQL = COALESCE(@SQL,'') + 'Kill ' + Convert(varchar, SPId) + ';'
    FROM MASTER..SysProcesses
    WHERE DBId = DB_ID(N'QLCC') AND SPId <> @@SPId
    EXEC(@SQL)
    DROP DATABASE [QLCC]
END
GO

/* Collation = SQL_Latin1_General_CP1_CI_AS */
CREATE DATABASE [QLCC]
GO

USE [QLCC]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[CAY]    Script Date: 5/30/2018 8:42:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAY](
	[ID_CAY] [nchar](10) NOT NULL,
	[TENCAY] [nvarchar](50) NOT NULL,
	[ID_LOAICAY] [nchar](10) NOT NULL,
	[ID_VITRI] [nchar](10) NOT NULL,
	[NGAYTRONG] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_CAY] PRIMARY KEY CLUSTERED 
(
	[ID_CAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAY] ADD CONSTRAINT LOAICAYCANH FOREIGN KEY ([ID_LOAICAY]) REFERENCES [dbo].[LOAICAY]([ID_LOAICAY])
ALTER TABLE [dbo].[CAY] ADD CONSTRAINT VITRICAY FOREIGN KEY ([ID_VITRI]) REFERENCES [dbo].[VITRI]([ID_VITRI])


USE [QLCC]
GO

/****** Object:  Table [dbo].[LOAICAY]    Script Date: 5/30/2018 8:44:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAICAY](
	[ID_LOAICAY] [nchar](10) NOT NULL,
	[TEN_LOAICAY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LOAICAY] PRIMARY KEY CLUSTERED 
(
	[ID_LOAICAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[VITRI]    Script Date: 5/30/2018 8:46:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VITRI](
	[ID_VITRI] [nchar](10) NOT NULL,
	[TEN_VITRI] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_VITRI] PRIMARY KEY CLUSTERED 
(
	[ID_VITRI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[CHAMSOC_CAY]    Script Date: 5/30/2018 8:53:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHAMSOC_CAY](
	[ID_CHAMSOC] [nchar](10) NOT NULL,
	[TG_CHAMSOC] [datetime2](7) NOT NULL,
	[ID_VATTU] [nchar](10) NOT NULL,
	[ID_CAY] [nchar](10) NOT NULL,
	[SL_CHAMSOC] [int] NOT NULL,
	[TT_CAY] [nvarchar](50) NOT NULL,
	[GHICHU] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_CHAMSOC_CAY] PRIMARY KEY CLUSTERED 
(
	[ID_CHAMSOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHAMSOC_CAY] ADD CONSTRAINT VATTU_CS FOREIGN KEY ([ID_VATTU]) REFERENCES [dbo].[VATTU]([ID_VATTU])
ALTER TABLE [dbo].[CHAMSOC_CAY] ADD CONSTRAINT CAY_CS FOREIGN KEY ([ID_CAY]) REFERENCES [dbo].[CAY]([ID_CAY])


USE [QLCC]
GO

/****** Object:  Table [dbo].[VATTU]    Script Date: 5/30/2018 8:58:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VATTU](
	[ID_VATTU] [nchar](10) NOT NULL,
	[TEN_VATTU] [nvarchar](50) NOT NULL,
	[ID_DONVI] [int] NOT NULL,
 CONSTRAINT [PK_VATTU] PRIMARY KEY CLUSTERED 
(
	[ID_VATTU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VATTU] ADD CONSTRAINT DONVI_TINH FOREIGN KEY ([ID_DONVI]) REFERENCES [dbo].[DONVI]([ID_DONVI])



USE [QLCC]
GO

/****** Object:  Table [dbo].[DONVI]    Script Date: 5/30/2018 9:00:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DONVI](
	[ID_DONVI] [int] NOT NULL,
	[TEN_DONVI] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DONVI] PRIMARY KEY CLUSTERED 
(
	[ID_DONVI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[LICHCHAMSOC]    Script Date: 5/30/2018 9:09:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LICHCHAMSOC](
	[ID_LICHCHAMSOC] [nchar](10) NOT NULL,
	[NGAYLAP] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_LICHCHAMSOC] PRIMARY KEY CLUSTERED 
(
	[ID_LICHCHAMSOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[LICHCT]    Script Date: 5/30/2018 9:15:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LICHCT](
	[ID_LICHCT] [nchar](10) NOT NULL,
	[ID_LICHCHAMSOC] [nchar](10) NOT NULL,
	[ID_CHAMSOC] [nchar](10) NOT NULL,
 CONSTRAINT [PK_LICHCT] PRIMARY KEY CLUSTERED 
(
	[ID_LICHCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LICHCT] ADD CONSTRAINT LICHCS FOREIGN KEY ([ID_LICHCHAMSOC]) REFERENCES [dbo].[LICHCHAMSOC]([ID_LICHCHAMSOC])
ALTER TABLE [dbo].[LICHCT] ADD CONSTRAINT CHAMSOC FOREIGN KEY ([ID_CHAMSOC]) REFERENCES [dbo].[CHAMSOC_CAY]([ID_CHAMSOC])

USE [QLCC]
GO

/****** Object:  Table [dbo].[BCCHIPHI]    Script Date: 5/30/2018 9:22:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BCCHIPHI](
	[ID_BCCHIPHI] [nchar](10) NOT NULL,
	[TG_BAOCAO] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_BCCHIPHI] PRIMARY KEY CLUSTERED 
(
	[ID_BCCHIPHI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[BCCT_CHIPHI]    Script Date: 5/30/2018 9:27:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BCCT_CHIPHI](
	[ID_BCCT_CHIPHI] [nchar](10) NOT NULL,
	[ID_BCCHIPHI] [nchar](10) NOT NULL,
	[ID_VATTU] [nchar](10) NOT NULL,
	[SOPHIEUMUA] [int] NOT NULL,
	[TONG_GT] [money] NOT NULL,
	[TYLE] [float] NOT NULL,
 CONSTRAINT [PK_BCCT_CHIPHI] PRIMARY KEY CLUSTERED 
(
	[ID_BCCT_CHIPHI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCCT_CHIPHI] ADD CONSTRAINT BC_CHIPHI FOREIGN KEY ([ID_BCCHIPHI]) REFERENCES [dbo].[BCCHIPHI]([ID_BCCHIPHI])
ALTER TABLE [dbo].[BCCT_CHIPHI] ADD CONSTRAINT VATTU_BC FOREIGN KEY ([ID_VATTU]) REFERENCES [dbo].[VATTU]([ID_VATTU])


USE [QLCC]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[BCTINHTRANG_CAY]    Script Date: 5/30/2018 10:47:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BCTINHTRANG_CAY](
	[ID_BCTT_CAY] [nchar](10) NOT NULL,
	[TG_BAOCAO] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_BCTINHTRANG_CAY] PRIMARY KEY CLUSTERED 
(
	[ID_BCTT_CAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [QLCC]
GO

/****** Object:  Table [dbo].[BCCT_TINHTRANGCAY]    Script Date: 5/30/2018 9:35:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BCCT_TINHTRANGCAY](
	[ID_BCCT_TINHTRANGCAY] [nchar](10) NOT NULL,
	[ID_BCTT_CAY] [nchar](10) NOT NULL,
	[ID_CAY] [nchar](10) NOT NULL,
 CONSTRAINT [PK_BCCT_TINHTRANGCAY] PRIMARY KEY CLUSTERED 
(
	[ID_BCCT_TINHTRANGCAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BCCT_TINHTRANGCAY] ADD CONSTRAINT BC_TTCAY FOREIGN KEY ([ID_BCTT_CAY]) REFERENCES [dbo].[BCTINHTRANG_CAY]([ID_BCTT_CAY])
ALTER TABLE [dbo].[BCCT_TINHTRANGCAY] ADD CONSTRAINT CAY_BC FOREIGN KEY ([ID_CAY]) REFERENCES [dbo].[CAY]([ID_CAY])

USE [QLCC]
GO

/****** Object:  Table [dbo].[PHIEUMUA_VT]    Script Date: 5/30/2018 10:22:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUMUA_VT](
	[ID_PHIEUMUA_VT] [nchar](10) NOT NULL,
	[NGAYMUAVT] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_PHIEUMUA_VT] PRIMARY KEY CLUSTERED 
(
	[ID_PHIEUMUA_VT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLCC]
GO

/****** Object:  Table [dbo].[PHIEUMUA_VTCT]    Script Date: 5/30/2018 10:31:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUMUA_VTCT](
	[ID_PHIEUMUA_CT] [nchar](10) NOT NULL,
	[ID_PHIEUMUA_VT] [nchar](10) NOT NULL,
	[DIACHIMUA] [nvarchar](50) NOT NULL,
	[SOLUONGMUA] [int] NOT NULL,
	[SOTIEN] [money] ,
	[ID_VATTU] [nchar](10) NOT NULL,
 CONSTRAINT [PK_PHIEUMUA_VTCT] PRIMARY KEY CLUSTERED 
(
	[ID_PHIEUMUA_CT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEUMUA_VTCT] ADD CONSTRAINT PHIEUMUAVT FOREIGN KEY ([ID_PHIEUMUA_VT]) REFERENCES [dbo].[PHIEUMUA_VT]([ID_PHIEUMUA_VT])
ALTER TABLE [dbo].[PHIEUMUA_VTCT] ADD CONSTRAINT VATTU_MUA FOREIGN KEY ([ID_VATTU]) REFERENCES [dbo].[VATTU]([ID_VATTU])

USE [QLCC]
GO

/****** Object:  Table [dbo].[QUIDINH]    Script Date: 6/27/2018 8:34:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QUIDINH](
	[ID_QD] [int] NOT NULL,
	[MONEY_MAX] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO